TellTheWorld/TellTheWorld/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tellings.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
]

TellTheWorld/tellings/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from tellings.views import *

app_name = 'tellings'
urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('about/', AboutPage.as_view(), name='about'),
    path('acceptableusage/', AcceptableUsagePage.as_view(), name='acceptableusage'),
    path('accountdeleted/', AccountDeletedPage.as_view(), name='accountdeleted'),
    path('addnewupdate/', AddNewUpdate.as_view(), name='addnewupdate'),
    path('addupdatemodal/', AddUpdateModal.as_view(), name='addupdatemodal'),
    path('addusercomment/', AddUserComment.as_view(), name='addusercomment'),
    path('blockedusers/', BlockedUserListView.as_view(), name='blockedusers'),
    path('blockuser/', BlockUser.as_view(), name='blockuser'),
    path('censortext/', CensorText.as_view(), name='censortext'),
    path('changepassword/', ChangePasswordPage.as_view(), name='changepassword'),
    path('changeuserdetails/', ChangeUserDetailsPage.as_view(), name='changeuserdetails'),
    path('checkuserpassword/', CheckUserPassword.as_view(), name='checkuserpassword'),
    path('deleteaccountmodal/', DeleteAccountModal.as_view(), name='deleteaccountmodal'),
    path('deleteusercomment/', DeleteUserComment.as_view(), name='deleteusercomment'),
    path('deleteuserpost/', DeleteUserPost.as_view(), name='deleteuserpost'),
    path('editusercomment/', EditUserComment.as_view(), name='editusercomment'),
    path('editusercomment/<int:pk>', EditUserComment.as_view(), name='editusercomment'),
    path('edituserpost/', EditUserPost.as_view(), name='edituserpost'),
    path('edituserpost/<int:pk>', EditUserPost.as_view(), name='edituserpost'),
    path('errorpage/', ErrorPage.as_view(), name='errorpage'),
    path('hasexceededmaxposts/', HasExceededMaxPosts.as_view(), name='hasexceededmaxposts'),
    path('hidepost/', HidePost.as_view(), name='hidepost'),
    path('hiddenposts/', HiddenPostListView.as_view(), name='hiddenposts'),
    path('loginmodal/', LoginModal.as_view(), name='loginmodal'),
    path('loginpage/', LoginView.as_view(template_name='tellings/loginpage.html'), name='loginpage'),
    path('missionstatement/', MissionStatementPage.as_view(), name='missionstatement'),
    path('myupdates/', MyUpdatesListView.as_view(), name='myupdates'),
    path('newupdates/', NewUpdatesListView.as_view(), name='newupdates'),
    path('privacypolicy/', PrivacyPolicyPage.as_view(), name='privacypolicy'),
    path('signup/', SignUpPage.as_view(), name='signup'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('termsandconditions/', TermsAndConditionsPage.as_view(), name='termsandconditions'),
    path('unblockuser/', UnblockUser.as_view(), name='unblockuser'),
    path('unhidepost/', UnhidePost.as_view(), name='unhidepost'),
    path('unhideuserposts/', UnhideUserPosts.as_view(), name='unhideuserposts'),
    path('usercomments/', UserCommentListView.as_view(), name='usercomments'),
]

TellTheWorld/tellings/models.py
from django.db import models
from django.conf import settings

class UserPost(models.Model):
    postID = models.AutoField(primary_key=True, db_column='postID')
    # db_column forces the use of this name (otherwise Django names it user_Id)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             db_column='user')
    dateOfPost = models.DateTimeField()
    postTitle = models.CharField(max_length=35)
    postText = models.CharField(max_length=255)
    dateOfEdit = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.postTitle

    @property
    def post_tags(self):
        "Returns a list of tagNames attached to the UserPost object."
        tagmaps = Tagmap.objects.filter(postID=self.postID)
        tagList = sorted([tag.tagID.tagName for tag in tagmaps])
        return tagList

    class Meta: 
        verbose_name = "UserPost"
        verbose_name_plural = "UserPosts"


class Tag(models.Model):
    tagID = models.AutoField(primary_key=True, db_column='tagID')
    tagName = models.CharField(max_length=15)

    def __str__(self):
        return self.tagName

    @property
    def first_char(self):
        "Returns the first character of the tag. Used for grouping in the listview"
        return self.tagName[0]

    class Meta: 
        ordering = ['tagName']
        verbose_name = "Tag"
        verbose_name_plural = "Tags"


class Tagmap(models.Model):
    tagmapID = models.AutoField(primary_key=True, db_column='tagmapID')
    postID = models.ForeignKey(UserPost, on_delete=models.CASCADE, db_column='postID')
    tagID = models.ForeignKey(Tag, on_delete=models.CASCADE, db_column='tagID')

    class Meta: 
        verbose_name = "Tagmap"
        verbose_name_plural = "Tagmaps"


class UserComment(models.Model):
    commentID = models.AutoField(primary_key=True, db_column='commentID')
    postID = models.ForeignKey(UserPost, on_delete=models.CASCADE, db_column='postID')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             db_column='user')
    dateOfComment = models.DateTimeField()
    commentText = models.CharField(max_length=255)
    dateOfEdit = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.commentText

    class Meta: 
        verbose_name = "UserComment"
        verbose_name_plural = "UserComments"


class DeletedAccount(models.Model):
    deleted_date = models.DateTimeField()
    deleted_reason = models.CharField(max_length=15)
    membership_length = models.PositiveIntegerField(default=0)  # in days

    class Meta: 
        verbose_name = "DeletedAccount"
        verbose_name_plural = "DeletedAccounts"


class BlockedUser(models.Model):
    """ When a user is blocked, the person who blocked them will no longer be able to see
        their posts, and the blocked user will no longer be able to see posts by the person
        who blocked them. """
    blockedUser = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='blockeduser_blockeduser_set',
                             db_column='blockedUser')
    blockedBy = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             related_name='blockedby_blockeduser_set',
                             db_column='blockedBy')

    def __str__(self):
        return self.blockedUser.username

    class Meta:
        verbose_name = "BlockedUser"
        verbose_name_plural = "BlockedUsers"
        

class HiddenPost(models.Model):
    postID = models.ForeignKey(UserPost, on_delete=models.CASCADE, db_column='postID')
    hideFrom = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                             db_column='hideFrom')

    def __str__(self):
        return self.postID.postTitle

    class Meta:
        verbose_name = "HiddenPost"
        verbose_name_plural = "HiddenPosts"

TellTheWorld/tellings/views.py
# Filename:     views.py
# Author:       Andrew Laing
# Email:        parisianconnections@gmail.com
# Last updated: 19/05/2020
# Description:  Contains the views for the website.

import django.utils.timezone
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.views import View, generic 

from tellings.forms import *
from tellings.page_extras import banned_words

from datetime import timedelta, timezone
import enum

# #########################################################################################
# SHARED ENUMS, FUNCTIONS AND VARIABLES ---------------------------------------------------
# -----------------------------------------------------------------------------------------

class StatusCode(enum.Enum):
    """ Enum containing the status codes returned in the response dictionaries"""
    ERROR = 0
    SUCCESS = 1
    CENSORED = 2
    INVALIDPASSWORD = 3


adminNameList = ['admin']
maxPostsPerDay = 4

def contains_banned_word(text):
    """ Tests if a text contains a banned word.
    
    :param text: A string to test for banned words.
    :returns: True if the text contains a banned word, otherwise false.
    """
    text = text.lower()
    for banned_word in banned_words:
        if banned_word in text:
            return True
    return False


def has_exceeded_max_posts(request): 
    """ Used to determine if the user has exceeded the max number of daily allowed posts.
    
    :param request: A dictionary-like object containing the HTTP POST parameters, 
                    sent by a site visitor. Note that admins can make as many posts
                    as they need to!
    :returns: True if the user has exceeded the max number of daily allowed posts, 
              otherwise false.
    """
    if request.user.username in adminNameList:
        return False

    current_userID = request.user.id
    startofday = django.utils.timezone.now().replace(hour=0, minute=0, second=0, microsecond=0) 
    startofday = startofday.replace(tzinfo=timezone.utc)

    numberOfPostsToday = UserPost.objects.filter(user=current_userID, dateOfPost__gt=startofday).count()

    return numberOfPostsToday >= maxPostsPerDay

def user_login(request):
    """ Handles user authentication.

    :param request: A dictionary-like object containing all HTTP POST parameters 
                    sent by a site visitor. 
    :returns: A redirect to a HTML page.
    """
    username = request.POST['username']
    password = request.POST['pwd']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/loginpage/')


# #########################################################################################
# PAGE VIEWS ------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------

class AboutPage(View):
    """ Creates the About us page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the About us page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        return render(request, 'tellings/about.html')

    def post(self, request):
        """ Handles POST requests for the About us page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if ('username' in request.POST) and ('pwd' in request.POST):
            return user_login(request)
        else:
            return render(request, 'tellings/about.html')


class AcceptableUsagePage(View):
    """ Creates the Acceptable Usage Policy page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the Acceptable Usage Policy page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        return render(request, 'tellings/acceptableusage.html')

    def post(self, request):
        """ Handles POST requests for the Acceptable Usage Policy page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if ('username' in request.POST) and ('pwd' in request.POST):
            return user_login(request)
        else:
            return render(request, 'tellings/acceptableusage.html')


class AccountDeletedPage(LoginRequiredMixin, View):
    """ Creates the Account Deleted page for the website, and handles user account deletion """
    http_method_names = ['post']

    def post(self, request):
        """ Handles POST requests for the Error page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if ('reason' in request.POST):
            return self.deleteAccount(request)
        else:
            return HttpResponseRedirect('/errorpage/')

    def deleteAccount(self, request):
        """ Handles deleting the user's account.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page if the account was deleted, otherwise
                  a redirect to the error page.
        """
        current_user = request.user
        now = django.utils.timezone.now()
        now = now.replace(tzinfo=timezone.utc)
        deleted_date = now
        date_joined = current_user.date_joined
        membership_length = deleted_date - date_joined

        data = {
            'deleted_reason': request.POST.get('reason', 'noreasongiven'),
            'deleted_date': deleted_date,
            'membership_length': membership_length.days,
        }

        form = DeleteAccountForm(data)

        if form.is_valid():
            form.save()
            logout(request)
            current_user.delete()
            return render(request, 'tellings/accountDeleted.html')            
        else:
            return HttpResponseRedirect('/errorpage/')


class BlockedUserListView(LoginRequiredMixin, generic.ListView):
    """ Creates the BlockedUser page for the website."""
    model = BlockedUser
    template_name = "tellings/blockeduser_list.html"
    paginate_by = 20
    http_method_names = ['get']
 
    def get_queryset(self):
        current_user = self.request.user
        qs = super().get_queryset()
        return qs.filter(blockedBy=current_user).order_by('blockedUser__username')


class ChangePasswordPage(LoginRequiredMixin, View):
    """ Creates the change password page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the Change Password page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        form = PasswordChangeForm(request.user)
        return render(request, 'tellings/changePassword.html', {'form': form})

    def post(self, request):
        """ Handles POST requests for the Change Password page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if 'old_password' in self.request.POST and 'new_password1' in self.request.POST:
            return self.changePassword(request)
        else:
            return HttpResponseRedirect('/errorpage/')

    def changePassword(self, request):
        """ Handles changing the user's password.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor.
        :param form: A Django form object.
        :returns: A HTML page.
        """
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return render(request, 'tellings/changePassword.html', 
                        {'message': _('Your password was successfully updated!'), 'form': form})
        else:
            return render(request, 'tellings/changePassword.html', {'form': form})


class ChangeUserDetailsPage(LoginRequiredMixin, View):
    """ Creates the change user details page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the Change User Details page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """  
        form = ChangeUserDetailsForm(instance=request.user)
        return render(request, 'tellings/changeUserDetails.html', {'form': form})

    def post(self, request):
        """ Handles POST requests for the Change User Details page.

        :param request: A dictionary-like object containing all HTTP POST parameters 

TellTheWorld/tellings/templates/tellings/blockeduser_list.html
{% extends 'tellings/base.html' %}
{% block title %}Tell the World{% endblock title %} 

{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     blockeduser_list.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 29/06/2020
 * Description:  Template used for creating the BlockedUsers html.
 * -------------------------------------------------------------------------------
{% endcomment %}

{% block content %}
<div class="container-fluid main-content"> 
  <main class="container">
    <header>
      <h1>BLOCKED USERS</h1>
    </header>

    {% if blockeduser_list %}
    <div class="row blockeduser-container">
      {% for item in blockeduser_list %}
      <div class="user-comment-container">
        <div class="align_between">
          <span class="user-comment-details align-panel-footer-text-left"><a class="blockeduser-link" href="{% url 'tellings:newupdates' %}?userName={{ item.blockedUser }}" onclick="return $.confirm_view_blockeduser_posts()">{{ item.blockedUser|upper }} </a></span>
          <div class="btn-group">
            <button type="button" class="btn btn-danger align-panel-footer-text-right " onclick="$.unblock_user('{{ item.blockedUser }}');">Unblock User</button>
          </div>
        </div>   
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div class="row white-inner-container">
      <h2>You have not blocked any users.</h2>
    </div> 
    {% endif %} 

    {% include "tellings/includes/pagination.html" %}
  </main>
</div>
{% endblock %}

TellTheWorld/tellings/templates/tellings/errorPage.html
{% extends 'tellings/base.html' %}
{% block title %}Tell the World{% endblock title %} 

{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     errorPage.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 14/04/2020
 * Description:  Template for the error page.
 * -------------------------------------------------------------------------------
{% endcomment %}

{% block content %}
<div class="container-fluid main-content"> 
  <div class="container">  
    <main class="row white-inner-container">
      <header>
        <h1>Error</h1>
      </header>

      <p>Oops! Something went wrong when processing your data.</p>
      <p>Please contact the site's administrator at <a href="mailto:admin@tellings.com?Subject=Website%20Error" target="_top">admin@tellings.com</a> and let us know as soon as possible</p>
    </main>       
  </div>
</div>
{% endblock %}

TellTheWorld/tellings/templates/tellings/myupdates_list.html
{% extends 'tellings/base.html' %}
{% block title %}Tell the World{% endblock title %} 

{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     myupdates_list.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 29/06/2020
 * Description:  Template used for the MyUpdates page.
 * -------------------------------------------------------------------------------
{% endcomment %}

{% block content %}

  <div class="container-fluid main-content"> 
    <main class="container currentUserUpdates" id="userUpdates">
      <header>
        <h1>MY UPDATES</h1>
      </header>
      
      {% if userpost_list %}
      {% load static %}
      {% regroup userpost_list by dateOfPost|date:"M. jS Y" as ordered_post_list %}

      {% for mypost in ordered_post_list %}
      <article>
        <h2 class="date-grouper">{{ mypost.grouper }}</h2>
        <div class="panel-group">
          {% for item in mypost.list %}
          {# Update panel #} 
            <div class="panel panel-default" id="panel_post_{{ item.postID }}">
              {# PANEL HEADER #} 
              <div class="panel-header">  
                {# Post title and username #}
                <div class="col-sm-8 panel-postTitle">
                  <p><a href="{% url 'tellings:myupdates' %}" name="{{ item.user }}">
                      {{ item.user }} says</a> ... <span id="postTitle_{{ item.postID }}">{{ item.postTitle }}</span></p>
                </div>

                {# Show collapse, edit/hide/delete dropdown #} 
                <div class="col-sm-4 align-panel-text-right">
                  {# View Update button #}
                  <button class="btn btn-info collapse_btn" data-toggle="collapse" data-target="#collapse{{ item.postID }}">View Update</button>
        
                  {# Only allow the user to edit their own posts #}
                  {% if current_username %}
                    {% if item.user.username == current_username %}
                    {# Edit post #}
                    <div class="btn-group">
                      <button type="button" class="btn dropdown-toggle post-cog-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{% static 'tellings/imgs/settings_cog.png' %}" alt="">
                        <span class = "caret"></span>
                      </button>

                      <div class="dropdown-menu dropdown-menu-right">
                        <li>
                          <a id="hide_post_{{ item.postID }}" onclick="$.hide_post({{ item.postID }});">Hide Post</a>
                        </li>
                        <li>
                          <a id="edit_post_{{ item.postID }}" onclick="$.edit_post({{ item.postID }});">Edit Post</a>
                        </li>
                        <li>
                          <a id="delete_post_{{ item.postID }}" onclick="$.delete_post({{ item.postID }});">Delete Post</a>
                        </li>  
                      </div>
                    </div>   
                    {% endif %}
                  {% endif %}
                </div>
              </div>              {# END OF Panel header #} 

              {# PANEL BODY #}
              <div id="collapse{{ item.postID }}" class="panel-collapse collapse">
                <div class="panel-body">
                  <p id="text_post_{{ item.postID }}">{{ item.postText }}</p>
                </div>
              </div>                

              <div class="panel-footer align_between"> 
                <span class="align-panel-footer-text-left last-edited-text">
                  {% if item.dateOfEdit %}
                  (Last edited on {{ item.dateOfEdit|date:"d/m/Y" }})
                  {% else %}
                    &nbsp;
                  {% endif %}
                </span>
                {# Add the tags #}
                <span class="align-panel-footer-text-right">
                {% for tag in item.post_tags %} 
                  <a class="tagLink" href="{% url 'tellings:myupdates' %}?tagName={{ tag }}" name="{{ tag }}">{{ tag }}</a>
                {% endfor %}  
                </span>          
              </div>

              {# COMMENT PANEL #}
              <div class="comment-panel panel-footer" id="comments{{ item.postID }}">
                <button class="btn btn-info reply_btn">Reply</button>
                <button class="btn btn-info view_comments_btn">View all comments</button>
                
                <div class="user-reply-section">
                  <textarea class="form-control user-comment-input-area"  
                            placeholder="Enter your reply" rows="2" cols="2"
                            name="postText" maxlength="254" required></textarea>
                  <button class="btn btn-info post_reply_btn">POST REPLY</button>
                  <button class="btn btn-info cancel_reply_btn">CANCEL</button>
                </div>
                                  
                <div class="user-comment-section">
                  <p class="user-comment-text">Be the first person to make a comment on this post.</p>
                </div>  
              </div>

            </div> {# END OF UPDATE PANEL #}

          {% endfor %}
        </div>     {# END OF PANEL GROUP #}
      </article>
      {% endfor %}

      {% else %}
      <div class="row white-inner-container">
        <h2>No results found.</h2>
      </div> 
      {% endif %}  

      {% include "tellings/includes/pagination.html" %}
    </main>
  </div>

{% endblock %}

TellTheWorld/tellings/templates/tellings/signup.html
{% extends 'tellings/base.html' %}
{% block title %}Tell the World{% endblock title %} 

{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     signup.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 19/05/2020
 * Description:  Template for the SignUp page.
 * -------------------------------------------------------------------------------
{% endcomment %}

{% block content %}

<div class="container-fluid main-content">
  <main class="container">
    <header>
      <h1>Sign Up</h1>
    </header>
    
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        {% for field in form %}
        <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        <div>
          <input 
            {% if field.name == "password1" or field.name == "password2" %}
                  type="password" class="form-control input-lg"
            {% else %}
                  type="text" class="form-control input-lg"
            {% endif %}
                  name="{{ field.name }}"
                  id="id_{{ field.name }}"

            {% if field.name == "username" %}
                  value="{{ field.value|default_if_none:'' }}" autofocus
            {% else %}
                  value="{{ field.value|default_if_none:'' }}"
            {% endif %}
          >
          <p class="help-text">{{ field.help_text }} </p>
        </div>
        {% endfor %}

        <p><input type="checkbox" name="terms" required> I have read and accept the <a href="{% url 'tellings:termsandconditions' %}" target="_blank">Terms and Conditions</a>.</p>
        <p><input type="checkbox" name="usage" required> I have read and agree to abide by the <a href="{% url 'tellings:acceptableusage' %}" target="_blank">Acceptable Usage Policy</a>.</p>
      </div>

      {% include "tellings/includes/formErrors.html" %}
      
      <div>
        <button type="submit" class="btn btn-success btn-block btn-lg">SAVE CHANGES</button>
      </div>  
    </form>

    <div>
      <a href="{% url 'tellings:index' %}" class="btn btn-danger btn-block btn-lg">CANCEL</a> 
    </div>>

  </main> 
</div>  
{% endblock %}

TellTheWorld/tellings/templates/tellings/tag_list.html
{% extends 'tellings/base.html' %}
{% block title %}Tell the World{% endblock title %} 

{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     tag_list.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 29/06/2020
 * Description:  Template used for the Tags page.
 * -------------------------------------------------------------------------------
{% endcomment %}

{% block content %}

<div class="container-fluid main-content"> 
  <main class="container">
    <header>
      <h1>SEARCH FOR POSTS BY TAG</h1>
    </header>
    
    <div class="row white-inner-container">

      <div class="glossary-search">       
        <div class="input-group col-sm-12 align-panel-text-right">
            <input type="text" id="search-field" size="17" maxlength="15" class="form-control input-md" placeholder="Search" />
            <button id="glossary-search-btn" class="btn btn-info" type="button">?</button>
        </div>
      </div>

      {# Script used for search tag suggestions and search field submit #}
      {# Placed here because urls loaded from static #}

      {% load static %}
      <script>
        
        $.perform_search = function() {
          var inputVal = $("#search-field").val();
          var searchURL = "{% url 'tellings:tags' %}?search=" + inputVal
          document.location.href = searchURL;
        };

        $("#search-field").on("keypress", function(e){
          if(e.which == 13){
            $.perform_search();
          }
        });

        $("#glossary-search-btn").on("click", function(e){
          $.perform_search();
        });

        var tagnames = new Bloodhound({
          datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
          queryTokenizer: Bloodhound.tokenizers.whitespace,
          prefetch: {
            url: "{% static 'tellings/data/tagNames.json' %}",
            filter: function(list) {
              return $.map(list, function(tagname) {
                return { name: tagname }; });
            }
          }
        });

        tagnames.initialize();

        $('#search-field').typeahead(null, {
          name: 'name',
          displayKey: 'name',
          source: tagnames
        });
      </script>

      <div class="glossary-filter"> 
        {% if glossary_filter %}
        {% for glossary in glossary_filter %}
        <a class="btn btn-link" href="{% url 'tellings:tags' %}?search={{ glossary }}">{{ glossary }}</a>
        {% endfor %}
        {% endif %}
      </div>

    </div>

    <div class="row white-inner-container">

      {% if tag_list %}
        {% regroup tag_list by first_char as first_char_list %}
        {% for sort_by_first_char in first_char_list %}
        <article>
          <h2>{{ sort_by_first_char.grouper|title }}</h2>

          <div class="page-vertical-divider">
            <hr>
          </div>

          {% for item in sort_by_first_char.list %}
          <p>
            <a href="{% url 'tellings:newupdates' %}?tagName={{ item.tagName }}" name="{{ item.tagName }}">{{ item.tagName }}</a>
          </p>
          {% endfor %}
        </article>  
        {% endfor %}
      {% else %}
      <article>
        {% if search %}
        <h2>{{ search }}</h2>

        <div class="page-vertical-divider">
          <hr>
        </div>
        
        {% endif %}
        <h2>No results found.</h2>
      </article>
      {% endif %}  
    </div>  

    {% include "tellings/includes/pagination.html" %}
  </main>
</div>

{% endblock %}