TellTheWorld/TellTheWorld/urls.py
# Uncomment next two lines to enable admin:
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tellings.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
]

TellTheWorld/tellings/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from tellings.views import *

app_name = 'tellings'
urlpatterns = [
    path('', IndexPage.as_view(), name='index'),
    path('about/', AboutPage.as_view(), name='about'),
    path('acceptableusage/', AcceptableUsagePage.as_view(), name='acceptableusage'),
    path('accountdeleted/', AccountDeletedPage.as_view(), name='accountdeleted'),
    path('addnewupdate/', AddNewUpdate.as_view(), name='addnewupdate'),
    path('addupdatemodal/', AddUpdateModal.as_view(), name='addupdatemodal'),
    path('addusercomment/', AddUserComment.as_view(), name='addusercomment'),
    path('blockedusers/', BlockedUserListView.as_view(), name='blockedusers'),
    path('blockuser/', BlockUser.as_view(), name='blockuser'),
    path('censortext/', CensorText.as_view(), name='censortext'),
    path('changepassword/', ChangePasswordPage.as_view(), name='changepassword'),
    path('changeuserdetails/', ChangeUserDetailsPage.as_view(), name='changeuserdetails'),
    path('checkuserpassword/', CheckUserPassword.as_view(), name='checkuserpassword'),
    path('deleteaccountmodal/', DeleteAccountModal.as_view(), name='deleteaccountmodal'),
    path('deleteusercomment/', DeleteUserComment.as_view(), name='deleteusercomment'),
    path('deleteuserpost/', DeleteUserPost.as_view(), name='deleteuserpost'),
    path('editusercomment/', EditUserComment.as_view(), name='editusercomment'),
    path('editusercomment/<int:pk>', EditUserComment.as_view(), name='editusercomment'),
    path('edituserpost/', EditUserPost.as_view(), name='edituserpost'),
    path('edituserpost/<int:pk>', EditUserPost.as_view(), name='edituserpost'),
    path('errorpage/', ErrorPage.as_view(), name='errorpage'),
    path('hasexceededmaxposts/', HasExceededMaxPosts.as_view(), name='hasexceededmaxposts'),
    path('hidepost/', HidePost.as_view(), name='hidepost'),
    path('hiddenposts/', HiddenPostListView.as_view(), name='hiddenposts'),
    path('loginmodal/', LoginModal.as_view(), name='loginmodal'),
    path('loginpage/', LoginView.as_view(template_name='tellings/loginpage.html'), name='loginpage'),
    path('missionstatement/', MissionStatementPage.as_view(), name='missionstatement'),
    path('myupdates/', MyUpdatesListView.as_view(), name='myupdates'),
    path('newupdates/', NewUpdatesListView.as_view(), name='newupdates'),
    path('privacypolicy/', PrivacyPolicyPage.as_view(), name='privacypolicy'),
    path('signup/', SignUpPage.as_view(), name='signup'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('termsandconditions/', TermsAndConditionsPage.as_view(), name='termsandconditions'),
    path('unblockuser/', UnblockUser.as_view(), name='unblockuser'),
    path('unhidepost/', UnhidePost.as_view(), name='unhidepost'),
    path('unhideuserposts/', UnhideUserPosts.as_view(), name='unhideuserposts'),
    path('usercomments/', UserCommentListView.as_view(), name='usercomments'),
]

TellTheWorld/tellings/forms.py
from django import forms
from django.conf import settings as djangoSettings
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext as _

from tellings.models import *

from datetime import datetime
import json


class ChangeUserDetailsForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class NewUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(
            max_length=254,
            required=True,
            label = _('Email Address'),
            help_text = _('Required. A valid email address'))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )      

    def save(self, commit=True):
        user = super(NewUserCreationForm, self).save(commit=False)

        if commit:
            user.save()

        return user


class DeleteAccountForm(forms.ModelForm):
    class Meta:
        model = DeletedAccount
        fields = ['deleted_date', 'deleted_reason', 'membership_length' ]   


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = UserComment
        fields = ('postID', 'user', 'dateOfComment', 'dateOfEdit', 'commentText') 


class UserPostForm(forms.ModelForm): 
    postTitle = forms.CharField(required=True,
                max_length=UserPost._meta.get_field('postTitle').max_length)
    postText =  forms.CharField(required=True,
                max_length=UserPost._meta.get_field('postText').max_length)


    def __init__(self, *args, **kwargs):
        self.tagList = False

        # pop post tags because this is not used to create a postRecord
        if len(args) > 0:
            if 'postTags' in args[0]:
                postTags = args[0].pop('postTags')
                self.tagList = json.loads(postTags[0])

        super(UserPostForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserPost
        fields = ['user', 'dateOfPost','postTitle', 'postText']  
     

    def save(self, commit=True):
        """ Used to save the UserPost record and create its Tagmap records.
        """
        post = super(UserPostForm, self).save(commit=False)

        if commit:
            post.save()

        if self.tagList:
            self.add_tag_and_tagmap_records(post) 

        return post
        
    def add_tag_and_tagmap_records(self, post):
        """ Used to add any new tags created with the post,
            and create Tagmaps for the post.
        """
        for tagName in self.tagList:
            tagName = tagName.lower()
            if Tag.objects.filter(tagName=tagName).exists():
                tag = Tag.objects.get(tagName=tagName)
            else:
                tag = Tag(tagName=tagName)
                tag.save()

            if not Tagmap.objects.filter(postID=post, tagID=tag).exists():
                tm = Tagmap(postID=post, tagID=tag)
                tm.save()  
        
        # Update the tagNames.json file used for tag completion
        self.update_tagnames_JSON_file()
       
    def update_tagnames_JSON_file(self): 
        """ Used to update the JSON file used for tag completion. """    
        updatedTags = list(Tag.objects.values_list('tagName', flat=True))

        with open(djangoSettings.TELLINGS_ROOT+'/static/tellings/data/tagNames.json', 'w') as f:
            json.dump(updatedTags, f)

TellTheWorld/tellings/views.py
# Filename:     views.py
# Author:       Andrew Laing
# Email:        parisianconnections@gmail.com
# Last updated: 19/05/2020
# Description:  Contains the views for the website.

import django.utils.timezone
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.views import View, generic 

from tellings.forms import *
from tellings.page_extras import banned_words

from datetime import timedelta, timezone
import enum

# #########################################################################################
# SHARED ENUMS, FUNCTIONS AND VARIABLES ---------------------------------------------------
# -----------------------------------------------------------------------------------------

class StatusCode(enum.Enum):
    """ Enum containing the status codes returned in the response dictionaries"""
    ERROR = 0
    SUCCESS = 1
    CENSORED = 2
    INVALIDPASSWORD = 3


adminNameList = ['admin']
maxPostsPerDay = 4

def contains_banned_word(text):
    """ Tests if a text contains a banned word.
    
    :param text: A string to test for banned words.
    :returns: True if the text contains a banned word, otherwise false.
    """
    text = text.lower()
    for banned_word in banned_words:
        if banned_word in text:
            return True
    return False


def has_exceeded_max_posts(request): 
    """ Used to determine if the user has exceeded the max number of daily allowed posts.
    
    :param request: A dictionary-like object containing the HTTP POST parameters, 
                    sent by a site visitor. Note that admins can make as many posts
                    as they need to!
    :returns: True if the user has exceeded the max number of daily allowed posts, 
              otherwise false.
    """
    if request.user.username in adminNameList:
        return False

    current_userID = request.user.id
    startofday = django.utils.timezone.now().replace(hour=0, minute=0, second=0, microsecond=0) 
    startofday = startofday.replace(tzinfo=timezone.utc)

    numberOfPostsToday = UserPost.objects.filter(user=current_userID, dateOfPost__gt=startofday).count()

    return numberOfPostsToday >= maxPostsPerDay

def user_login(request):
    """ Handles user authentication.

    :param request: A dictionary-like object containing all HTTP POST parameters 
                    sent by a site visitor. 
    :returns: A redirect to a HTML page.
    """
    username = request.POST['username']
    password = request.POST['pwd']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/loginpage/')


# #########################################################################################
# PAGE VIEWS ------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------

class AboutPage(View):
    """ Creates the About us page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the About us page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        return render(request, 'tellings/about.html')

    def post(self, request):
        """ Handles POST requests for the About us page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if ('username' in request.POST) and ('pwd' in request.POST):
            return user_login(request)
        else:
            return render(request, 'tellings/about.html')


class AcceptableUsagePage(View):
    """ Creates the Acceptable Usage Policy page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the Acceptable Usage Policy page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        return render(request, 'tellings/acceptableusage.html')

    def post(self, request):
        """ Handles POST requests for the Acceptable Usage Policy page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if ('username' in request.POST) and ('pwd' in request.POST):
            return user_login(request)
        else:
            return render(request, 'tellings/acceptableusage.html')


class AccountDeletedPage(LoginRequiredMixin, View):
    """ Creates the Account Deleted page for the website, and handles user account deletion """
    http_method_names = ['post']

    def post(self, request):
        """ Handles POST requests for the Error page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if ('reason' in request.POST):
            return self.deleteAccount(request)
        else:
            return HttpResponseRedirect('/errorpage/')

    def deleteAccount(self, request):
        """ Handles deleting the user's account.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page if the account was deleted, otherwise
                  a redirect to the error page.
        """
        current_user = request.user
        now = django.utils.timezone.now()
        now = now.replace(tzinfo=timezone.utc)
        deleted_date = now
        date_joined = current_user.date_joined
        membership_length = deleted_date - date_joined

        data = {
            'deleted_reason': request.POST.get('reason', 'noreasongiven'),
            'deleted_date': deleted_date,
            'membership_length': membership_length.days,
        }

        form = DeleteAccountForm(data)

        if form.is_valid():
            form.save()
            logout(request)
            current_user.delete()
            return render(request, 'tellings/accountDeleted.html')            
        else:
            return HttpResponseRedirect('/errorpage/')


class BlockedUserListView(LoginRequiredMixin, generic.ListView):
    """ Creates the BlockedUser page for the website."""
    model = BlockedUser
    template_name = "tellings/blockeduser_list.html"
    paginate_by = 20
    http_method_names = ['get']
 
    def get_queryset(self):
        current_user = self.request.user
        qs = super().get_queryset()
        return qs.filter(blockedBy=current_user).order_by('blockedUser__username')


class ChangePasswordPage(LoginRequiredMixin, View):
    """ Creates the change password page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the Change Password page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        form = PasswordChangeForm(request.user)
        return render(request, 'tellings/changePassword.html', {'form': form})

    def post(self, request):
        """ Handles POST requests for the Change Password page.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """
        if 'old_password' in self.request.POST and 'new_password1' in self.request.POST:
            return self.changePassword(request)
        else:
            return HttpResponseRedirect('/errorpage/')

    def changePassword(self, request):
        """ Handles changing the user's password.

        :param request: A dictionary-like object containing all HTTP POST parameters 
                        sent by a site visitor.
        :param form: A Django form object.
        :returns: A HTML page.
        """
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return render(request, 'tellings/changePassword.html', 
                        {'message': _('Your password was successfully updated!'), 'form': form})
        else:
            return render(request, 'tellings/changePassword.html', {'form': form})


class ChangeUserDetailsPage(LoginRequiredMixin, View):
    """ Creates the change user details page for the website."""
    http_method_names = ['get', 'post']

    def get(self, request):
        """ Handles GET requests for the Change User Details page.

        :param request: A dictionary-like object containing all the HTTP parameters 
                        sent by a site visitor. 
        :returns: A HTML page.
        """  
        form = ChangeUserDetailsForm(instance=request.user)
        return render(request, 'tellings/changeUserDetails.html', {'form': form})

    def post(self, request):
        """ Handles POST requests for the Change User Details page.

        :param request: A dictionary-like object containing all HTTP POST parameters 

TellTheWorld/tellings/templates/tellings/includes/JSMessagePopup.html
{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     JSMessagePopup.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 14/04/2020
 * Description:  This is used to create a JavaScript message popup.
 * -------------------------------------------------------------------------------
{% endcomment %} 

{% block messages %}
{% if message %}
<script>
    alert('{{ message }}');
</script>            
{% endif %}
{% endblock %}

TellTheWorld/tellings/templates/tellings/includes/addUpdate_modal.html
{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     addUpdate_modal.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 23/06/2020
 * Description:  This is used to create the addUpdate modal.

 * Note:         Files which include this modal must extend base.html.
 * -------------------------------------------------------------------------------
{% endcomment %} 

{% load static %}
{# START OF #addUpdateModal #}
<div class="modal fade" id="addUpdateModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">

      {# MODAL HEADER #}
      <div class="modal-header">
        <button type="button" class="close" aria-label="Close" data-dismiss="modal" aria-hidden="true"><span style="">&times;</span></button>
        <h2>Add new update</h2>
      </div>

      {# MODAL BODY #}
      <div class="modal-body">
        <form role="form" name="frmAddUpdate" id="frmAddUpdate" action="javascript:void(0);">
          {% csrf_token %}
          <div class="form-group">
            <label for="postTitle">Title</label>
            <br />
            <input type="text" class="form-control" id="postTitle" name="postTitle" 
                   placeholder="Enter a unique title for your post ..." maxlength="34" required>
            <br />

            <label for="postText">Text</label>
            <br />
            <textarea placeholder="Enter post text" rows="7" class="form-control" id="postText" 
                   name="postText" maxlength="254" required></textarea>
            <br />

            <label for="postTags">Tags</label>  - (<i>Words used to categorise your post</i>)
            <br />

            <div id="tagDiv">
              <input type="text" class="form-control" id="postTags" name="postTags" data-role="tagsinput" maxlength="49"/>
            </div>    
            
            {# Script used for tag suggestions #}
            <script>
              var tagnames = new Bloodhound({
                  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                  queryTokenizer: Bloodhound.tokenizers.whitespace,
                  prefetch: {
                    url: "{% static 'tellings/data/tagNames.json' %}",
                    filter: function(list) {
                      return $.map(list, function(tagname) {
                        return { name: tagname }; });
                    }
                  }
                });

                tagnames.initialize();

                $('#tagDiv').tagsinput({
                  typeaheadjs: {
                    name: 'tagnames',
                    displayKey: 'name',
                    valueKey: 'name',
                    source: tagnames.ttAdapter()
                  }
                });
                
                // Add entered tag if user exits without confirming it
                $('#tagDiv').tagsinput('input').blur(function() {
                  $('#tagDiv').tagsinput('add', $(this).val());
                  $(this).val('');
                });

            </script>
          </div>

          <div class="modal-vertical-divider">
            <hr>
          </div>

          <div class="modal-action-btn">
            <button type="button" class="btn btn-success btn-block" id="addNewUpdatePostBtn" 
                    value="postBtn" >POST UPDATE</button>
          </div>      
          <div class="modal-action-btn">
            <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">CANCEL</button> 
          </div>     

        </form>
      </div>

    </div>        {# End of .modal-content #}
  </div>          {# End of .modal-dialog #}
</div>            {# End of #addUpdateModal #} 

TellTheWorld/tellings/templates/tellings/includes/deleteAccount_modal.html
{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     deleteAccount_modal.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 23/06/2020
 * Description:  This is used to create the deleteAccount modal.

 * Note:         Files which include this modal must extend base.html.
 * -------------------------------------------------------------------------------
{% endcomment %} 

{% load static %}

{# START OF #deleteAccountModal #}
<div class="modal fade" id="deleteAccountModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">

      {# MODAL HEADER #}
      <div class="modal-header">
        <button type="button" class="close" aria-label="Close" data-dismiss="modal" aria-hidden="true"><span style="">&times;</span></button>
        <h2>Delete Your Account</h2>
      </div>
      
      {# MODAL BODY #}
      <div class="modal-body">
      
        <p>Hi,</p>
        <p>We're sorry to hear that you want to delete your account and hope that you have enjoyed the time spent with us.</p>
        <br>
        <p><strong>Protecting Your Data</strong></p>
        <p>We take the safety and security of the Tell the World community very seriously. People place their trust in us when they share their hopes and dreams on Tell the World. We will make no compromises when it comes to safeguarding your data.</p>   
        
        <div class="modal-vertical-divider">
          <hr>
        </div>
        
        <form role="form" name="frmDeleteAccount" id="frmDeleteAccount" action="javascript:void(0);">
          {% csrf_token %}
          
          <div class="form-group">
            <label for="reasonsList">Why are you deleting your account?</label>
            <br />
            <select class="form-control" name="reasonsList" id="reasonsList">
               <option value="somethingelse">Something else</option>
               <option value="difficulttouse">Too difficult to use</option>
               <option value="bullying">Online bullying</option>
               <option value="privacy">Privacy concerns</option>
               <option value="oldaccount">I created a new account</option>
               <option value="nofriends">Cannot find people to share with</option>
               <option value="toomanyads">Too many ads</option>
               <option value="removeallposts">To remove all posts</option>
            </select>
            <br>

            <label for="pwd">To continue, please re-enter your password</label>
            <br />
            <input type="password" class="form-control" id="pwd_deleteModal" name="pwd_deleteModal"  placeholder="Enter password" maxlength="50">
            <p><a href="mailto:admin@tellings.com?Subject=Forgotten%20Password">Forgotten your Password?</a></p>
            <br />
            <p>When you press the button below, your posts and all other data will be removed forever and will not be recoverable in the future.</p>

            <div class="modal-vertical-divider">
              <hr>
            </div>
          </div>
          <div class="modal-action-btn">
            <button type="submit" class="btn btn-success btn-block" name="deleteBtn" 
                    value="deleteBtn" onClick="return $.validate_deleteAccount();">PERMANENTLY DELETE MY ACCOUNT</button>
          </div>      
          <div class="modal-action-btn">
            <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">CANCEL</button> 
          </div>     

        </form>
      </div>

    </div>      {# End of .modal-content #}
  </div>        {# End of .modal-dialog #}
</div>          {# End of #deleteAccountModal #}  

TellTheWorld/tellings/templates/tellings/includes/footerContents.html
{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     footerContents.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 14/04/2020
 * Description:  This contains the HTML footer which should be added to all pages.

 * Note:         Files which include this script must also extend base.html.
 * -------------------------------------------------------------------------------
{% endcomment %}
  {# BUSINESS ADDRESS #}
  <div class="col-sm-3 footerDivs">
    <h2>Business Address</h2>
    <p>TTW Ltd<br />1-3 Rumford Street,<br /> Liverpool <br />L2 8SZ</p>
  </div>
  
  {# CONTACT DETAILS #}
  <div class="col-sm-3 footerDivs">
    <h2>Contact Us</h2>
    <p>
       Telephone: <a href="tel:01512272008">0151 227 2008</a><br />
       Email: <a href="mailto:info@telltheworld.com?Subject=Website%20contact" target="_top">info@telltheworld.com</a><br />
       Skype: <a href="skype:telltheworld?call">telltheworld</a>
	  </p>
  </div>
  
  {# OFFICE HOURS DETAILS #}
  <div class="col-sm-3 footerDivs">
    <h2>Office Hours</h2>
    <p>7 days a week<br />08:00am-18:00pm</p>
  </div>

  {# SOCIAL MEDIA DETAILS #}
  <div class="col-sm-3 footerDivs">
    <h2>Follow us</h2>
    <div>
      <p>
        <a class="btn btn-icon btn-facebook" href="https://www.facebook.com/westernapproachesHQ/">f</a>
        <a class="btn btn-icon btn-twitter" href="https://twitter.com/WestApproaches">t</a>
      </p>   
    </div>
    <div>
      <p>
        <a href="{% url 'tellings:acceptableusage' %}">Acceptable Usage Policy</a><br />
        <a href="{% url 'tellings:privacypolicy' %}">Privacy Policy</a><br />
        <a href="{% url 'tellings:termsandconditions' %}">Terms and Conditions</a>
      </p>         
    </div>
  </div>

TellTheWorld/tellings/templates/tellings/includes/navbar.html
{% comment %} 
 * -------------------------------------------------------------------------------
 * Filename:     navbar.html
 * Author:       Andrew Laing
 * Email:        parisianconnections@gmail.com
 * Last updated: 14/04/2020
 * Description:  This is used to create the navbar according to the user's 
 *               logged in status.

 * Note:         Files which include this script must also extend base.html.
 * -------------------------------------------------------------------------------
{% endcomment %} 

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'tellings:index' %}">Home</a>
  </div>

  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    {# LEFT NAVBAR #}
    <ul class="nav navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tellings:newupdates' %}">New Updates</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tellings:tags' %}">Tags</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tellings:myupdates' %}">My Updates</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="addUpdateBtn" href="javascript:void(0);">Add New Update</a>
      </li>
      {% endif %}
    </ul>

    {# RIGHT NAVBAR #}
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">About</a>
        <ul class="dropdown-menu">
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:about' %}">About us</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:missionstatement' %}">Mission Statement</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:acceptableusage' %}">Acceptable Usage Policy</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:privacypolicy' %}">Privacy Policy</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:termsandconditions' %}">Terms and Conditions</a>
          </li>
        </ul>

      {% if user.is_authenticated %}
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Account</a>
        <ul class="dropdown-menu">
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:changeuserdetails' %}">Change Account Details</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:changepassword' %}">Change Password</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" id="deleteAccountBtn" href="javascript:void(0);">Delete My Account</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link" href="{% url 'tellings:hiddenposts' %}">Hidden Posts</a>
          </li>
          <li class="nav-item dropdown-menu-item">
            <a class="nav-link"  href="{% url 'tellings:blockedusers' %}">Blocked Users</a>
          </li>
        </ul>
      </li>
      <li class="nav-item">
        <a href="{% url 'logout' %}" onclick="return $.confirm_logout();">Log out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tellings:signup' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a href="javascript:void(0);" id="loginBtn">Login</a>
      </li>
      {% endif %}
    </ul>

</div>